version: '3.7'

# 컴퓨터들
services:

  # 첫번째 컴퓨터 이름
  class_build:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  # 두번째 컴퓨터 이름
  # ...똑같이 작성하면 된다. 여러 컴퓨터를 한번에 묶어서 동시에 실행할 수 있다.
